import { HackingMessage } from './types';

export const FRIENDS_LIST = [
  // Combined list of names for flashing effect, with duplicates removed.
  "उत्सुक निरौला", "Sharada Aryal Adhikari", "Mukti Adhikari", "Kushal Kadel",
  "Asmita Poudel Asmita", "Prasanna Dev", "Sumitra Ghimire", "Succe S S Adhikari",
  "Aarati Bhattarai Adhikari", "Shova Khanal", "Aseem Dhungana", "Manu Aryal",
  "Rishi Ram Ghimire", "Pranjal Subedi", "Mina Adhikari", "Unnat Thapa",
  "Tulsi Baral", "Nirmala Adhikari", "Ritik Dhungana", "Dipendra Subedi",
  "Mission Adhikari", "Purnima Acharya", "Gauri Aryal", "Sadish Lamichhane",
  "Balaram Aryal", "Bamdev Sapkota", "Nabina Sapkota", "Aayush Subedi",
  "Himamshu Paudel", "Anurag Kafle", "Rudranath Sapkota", "Nabraj Adhikari",
  "Prabala Khanal", "Nishan Adhikari", "Somraj Koirala", "Rishi Regmi",
  "Seajal Pun", "Arp Ann", "Subas Bhusal", "Bhawani Aryal", "Abhishek Chalise",
  "Susan Neupane", "Shahil Chaudhary", "Nabin Khanal", "Kabita Rijal",
  "Janardan Khanal", "Dipesh Adhikari", "Aaditya Subedi", "Suraj Acharya",
  "Parbati Khanal", "Utsab Dawadi", "Aryal Milan", "Rajkumar Basnet",
  "अनुप धिताल", "Susma Aryal", "बाबुराम अर्याल", "Amrita Poudel", "Keshav Ydv",
  "Keshav Yadav", "Radhika Basnet", "नितेश श्रेष्ठ", "Dipa Subedi",
  "Rajan Yadav", "Karuna Sapkota", "Bishal Yadav", "Ganga Maya Aryal",
  "Sabin Ramdam", "Subash Aryal", "Parbati Aryal", "Saman Darai", "Mansika Aryal",
  "Kalpana Kandel", "Madhu Aryal", "Krishan Sharma", "Dilip Subedi",
  "Lila Khanal", "Chunu Subedi", "Shreejay Tiwari", "सुरज रेग्मी",
  "Khanal Rajesh", "Ambika Subedi", "राज परियार", "Pramesh Rana",
  "शरोज पोख्रेल", "Bishal Khanal", "Aashish Subedi", "Dilli Prd Subedi",
  "Khanal Kancha Khanal", "Pratima Kattel", "Radha Poudel", "Dibyanka Dibyansha",
  "Regmi Narayan", "Samir Baral", "Durga Khanal", "Retina Aayan", "Rohan Dhakal",
  "Deependra Aryal", "Rajkumar Kandel", "Susan Khanal", "Nirose Bastola",
  "Bimal Chhetri", "Kripesh Bhusal", "Abhinab Adhikari", "Onive Bastakoti",
  "Ranju Bhandari", "Keshav Giri", "RtrDinanath Dhungana", "मामा घर",
  "Shirish Karki", "PRince KaflE", "Nischaya Khatri", "Anam Shrestha",
  "Jayaram Khatri", "Suyog Chandra Sadashankar", "Aditya Neupane",
  "Cris Bek Nald", "Ramesh Basaula", "Shova Barali", "Suyog Paudel",
  "Anjana Kandel", "Sur Ya", "Aarjan Adhikari", "Prashmsa Parajuli",
  "Narayani Sapkota Narayani", "Radha Adhikari", "Sushman Jung Kunwar",
  "Chitrabahadur Sunar", "Shambhawi Sedai", "Sambandha Poudel", "Arpit Poudel",
  "Barshika Barali", "Parbata Adhikari", "Shubham Spk", "Ishu Lamichhane",
  "Sagar Poudel", "Rajeev Chaudhary", "अस्विन सापकोटा", "मणि दवाडी",
  "Aayam Gautam", "Krishma Senchury", "Rishav Gautam", "Krish Kunwar",
  "Jaya Ram KC", "Suyog Devkota", "Sharda Barali", "Ñi Rm Ál",
  "Utsav Parajuli", "Arjun Das Tharu", "Sarita Panta Dawadi", "Anil Sunar",
  "Daktar Raut", "Nikesh Kandel", "Pramish Tripathi", "एन्जिल पाठक",
  "निपुन सेढाई", "Prasant Sunar", "Ronish Kc", "PraSi Ddha",
  "Buddhi Sentury", "Sahan Kandel", "Adip Giri", "Supriya Rasaili",
  "Äayan Ãcharya", "Anupa Sunchiuri", "Sab In", "Ronish Kshetri",
  "Khatri Preju", "Åjåy Adhikari", "Dilkumari Barali", "Gaurav Thapa",
  "Nirmal Lamichhane", "Indira Sadashankar", "Yugesh Gupta",
  "Sabita Rasaily", "Sam Yam", "Gaurav Gupta", "Nitin Upadhyaya",
  "Amrita Kunwar", "Rashik Shrestha", "Kritan Bahadur Shrestha",
  "Susan Rimal", "Anam Stha", "Sachina Barali", "Shubham BK",
  "Rupa Gurung Barali", "Khushi Sunar", "Asha nursing college chitwan",
  "Yam Bk", "Diwash Lal Bhumi Sth", "Niva Kharel", "Sarmila Sadhashankar",
  "Hrithik Yadav", "Saru Sunar", "Ab Sunar", "Chitwan Nepal",
  "Jyoti Shrestha", "Deepak Pradhan", "Muskan Sunar", "Aashish Sah",
  "Binod Gajmer", "Mahendra Bikram Adhikari", "Ranendra Barali",
  "माननीय रणेन्द्र बराली सचिवालय", "अयान घिमिरे", "Rama Barali",
  "Anukul Shrestha", "Gyanendra Barali", "Nabin Das", "Sankar Pal",
  "Ku-cal C-restha", "Divya Ghimire", "Saugat Sadashankar",
  "Seti Bishowkarma", "Roshan Thapa", "Samundra Barali", "Raj Yadav",
  "Sunita Khadkathoki", "Ràñjáñ Bhãñdåry", "Hari Sunar", "Umesh Sunar",
  "Seemon Gautam", "Su-love Thakuri", "Bishnu Bishnu", "Ankita Sonar",
  "Ankit Sah", "Sharmila Gautam", "Bipin Ramudamu", "Kishore Thapa",
  "Kamal Senchury", "Gyanmani Sadashankar", "Sharad Gopal Nyachhyon",
  "Bsal Bhatrai", "Dhan Maya Sunar", "Jyoti Ghimire", "Krishna Sunar",
  "Sumit Magar", "Purn Sunar", "Prakash Sunar", "Sumit Chavan",
  "Netra Panthi", "PraTyush Shres Tha", "Padam Sunar", "Twinkle Sonar",
  "Shobha Barali", "Dhanu Sunar", "Amity University", "Radha Sonar",
  "Upendra Barali", "Abhas Khati", "Grg Kumari", "Omgi Kumar Sarraf",
  "Naina Sunar", "Nikesh Regmi", "Kazuno Kai", "Prashamsa Sentury",
  "Shirish Pokharel", "Sequence Wallah", "Sushant Magar", "Manoj Nepali",
  "Dhanu Pokhrel", "Zoro Luffy", "यस ज्वेलर्स", "Bry An", "Aakash Barali",
  "Kritika Shrestha", "L　A　U　 R　E　Y　シ　︎", "Govinda Barali",
  "Samriddha Sadashankar", "Progress Ghimire", "Ranjan Shrestha",

  // Original, more important names at the end
  "Rahul Paudel", "Sachin Ghimire", "Saugat Adhikari", "Shrestha Saurya",
  "Sisir Panta", "Somendra Pant", "Success Adhikari", "Abhishek Panta",
  "Amulya Bogati", "Ashesh Panta", "Bibash Shrestha", "Himanshu Ghimire",
  "Krish Sapkota", "Nikson Pulami", "Nishan Jung Rayamajhi", "Prabal Lama",
  "Vijan Adhikari",
];

export const HACKING_MESSAGES: HackingMessage[] = [
  { text: "Initializing Stalker Protocol v3.1...", type: 'fast' },
  { text: "Target locked: {userName}", type: 'fast', delayBefore: 200 },
  { text: "Bypassing global firewalls... [OK]", type: 'fast', delayBefore: 500 },
  { text: "Injecting SQL query into Facebook mainframe...", type: 'slow', delayBefore: 1000 },
  { text: "Access granted. Retrieving known associates...", type: 'fast', delayBefore: 1500 },
  { text: "Scanning profiles...", type: 'data', delayBefore: 500 },
  { text: "Cross-referencing photo tags and geo-locations...", type: 'fast', delayBefore: 2000 },
  { text: "Compiling list of high-interaction profiles...", type: 'slow', delayBefore: 1000 },
  { text: "No primary suspects found among known associates.", type: 'slow', delayBefore: 2500 },
  { text: "But wait...", type: 'slow', delayBefore: 2000 },
  { text: "I'm researching everything about you...", type: 'slow', delayBefore: 1500 },
  { text: "Every digital footprint. Every connection.", type: 'fast', delayBefore: 1000 },
  { text: "So... that makes me...", type: 'slow', delayBefore: 2500 },
  { text: "oh no... no no no...", type: 'final', delayBefore: 1000 },
  { text: "wait... wait... wait...", type: 'final', delayBefore: 1500 },
  { text: "Finalizing conclusion...", type: 'final', delayBefore: 2000 },
];